### ISSUE TITLE
Your repository is containing unnecessary folders like .vs, obj and bin folders.

### ISSUE THREAD

**Issue by TanvirArjel** [karnishalzz/TailorApp#1]
Your repository is containing unnecessary folders like **.vs, obj, and bin** folders. These folders should not be committed with source code. Please add `.gitignore` file for Visual Studio in your repository.

**Comment by karnishalzz** [comment]
okay bhaia.

**Comment by TanvirArjel** [comment]
Has been done with https://github.com/karnishalzz/TailorApp/commit/622d98a1e8f1bd6aa1b420893bb49c4155cd46dd
